# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoneyTarget' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MoneyTarget


  target 'MoneyTargetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MoneyTargetUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
